packages:
  - apps/*
  - packages/*

catalog:
  '@nestjs/cli': ^11.0.0
  '@nestjs/common': ^11.0.1
  '@nestjs/config': ^4.0.2
  '@nestjs/core': ^11.0.1
  '@nestjs/platform-express': ^11.0.1
  '@nestjs/schematics': ^11.0.0
  '@prisma/adapter-pg': ^7.1.0
  '@prisma/client': ^7.1.0
  '@types/node': ^24.10.1
  dotenv: ^17.2.3
  eslint: ^9.39.1
  nestjs-prisma: ^0.26.0
  nestjs-zod: ^5.0.1
  prettier: ^3.7.4
  reflect-metadata: ^0.2.2
  remeda: ^2.32.0
  rxjs: ^7.8.1
  tsdown: ^0.17.1
  tsx: ^4.21.0
  type-fest: ^5.3.1
  typescript: ^5.9.3
  zod: ^4.1.13

useNodeVersion: 24.11.1
